spring:
  application:
    name: taskapi
    admin:
      enabled: true
  datasource:
    url: "jdbc:mysql://localhost:3306/taskdb"
    username: root
    password: my-secret-pw
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    defer-datasource-initialization: true
escordev:
  openapi:
    dev-url: http://localhost:8080
    prod-url: https://bezkoder-api.com